In [174]:
import numpy as np 
import pandas as pd
import sys
from sklearn.tree import DecisionTreeClassifier

In [178]:
my_data = pd.read_csv("data.csv", delimiter=",")
my_data[0:5]

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (7,13,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


NPI                PROVIDERNAME  ENTITY_TYPE_CODE  \
0  1396819231  GUSKY-SHARP, KATHLEEN NONE                 1   
1  1194890707      TARTLER, ADRIAN LASZLO                 1   
2  1003981614          MONIKA RUKUS, INC.                 2   
3  1912072521          JAFORD ENTERPRISES                 2   
4  1992870505               OLANO, ANNA A                 1   

  P_O_N_LEGAL_BUSINESS_NAME     P_F_L_B_M_ADDRESS PROV_B_M_A_CITY_NAME  \
0                       NaN     105 VISTA VIEW DR           CLOVERDALE   
1                       NaN      311 N QUENTIN ST              WICHITA   
2        MONIKA RUKUS, INC.  8901 CONNECTICUT AVE          CHEVY CHASE   
3        JAFORD ENTERPRISES          PO BOX 86028          BATON ROUGE   
4                       NaN  100 E IRVING PARK RD              ROSELLE   

  PROV_B_M_A_STATE_NAME PROV_B_M_A_POSTAL_CODE PROV_B_M_A_CNT_CODE_OUT_US  \
0                    CA              954253373                         US   
1                    KS              672083714                         US   
2                    MD              208156734                         US   
3                    LA              708796028                         US   
4                    IL              601722048                         US   

  PROV_B_M_A_TELEPHONE_NUMBER            ...             AUTH_OFF_FRST_NAME  \
0                  7078947409            ...                            NaN   
1                  3166509187            ...                            NaN   
2                  3019869999            ...                         MONIKA   
3                  2252910325            ...                       SHEVELLE   
4                  6304390009            ...                            NaN   

  AUTH_OFF_MIDDLE_NAME AUTH_OFF_TITLE_OR_POSITION AUTH_OFF_TELEPHONE_NUMBER  \
0                  NaN                        NaN                       NaN   
1                  NaN                        NaN                       NaN   
2                   L.                      OWNER                3019869999   
3                LIESA                        PIC                2252910325   
4                  NaN                        NaN                       NaN   

  H_P_T_CODE_1 PROV_LIC_NUM_1 PROV_LIC_NUM_STATE_CODE_1 H_P_P_T_SWITCH_1  \
0   171W00000X        CAOT#12                        CA                Y   
1   111NI0900X        T-00986                        KS                Y   
2   101YM0800X          08641                        MD                Y   
3   3336C0003X           4058                        LA                Y   
4   225100000X     070-008093                        IL                Y   

  PRIMARY_TAXONOMY                   SPECDESC  
0       171W00000X                 Contractor  
1       111NI0900X                  Internist  
2       101YM0800X              Mental Health  
3       3336C0003X  Community/Retail Pharmacy  
4       225100000X         Physical Therapist  

[5 rows x 29 columns]

In [176]:
my_data= my_data[0:1000]

In [177]:

sys.getsizeof(my_data)/(1024*1024*1024)
np.unique(my_data["PROV_B_M_A_STATE_NAME"])

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN',
       'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [161]:
X = my_data[['ENTITY_TYPE_CODE',  'PROV_B_M_A_STATE_NAME', 'PROV_B_M_A_POSTAL_CODE', 'SPECDESC']].values
X[0:3]

array([[1, 'CA', '954253373'],
       [1, 'KS', '672083714'],
       [2, 'MD', '208156734']], dtype=object)

In [162]:
from sklearn import preprocessing
le_STATE_NAME = preprocessing.LabelEncoder()
le_STATE_NAME.fit(np.unique(my_data["PROV_B_M_A_STATE_NAME"]))
X[:,1] = le_STATE_NAME.transform(X[:,1]) 




In [163]:
X[0:100]

array([[1, 4, '954253373'],
       [1, 16, '672083714'],
       [2, 20, '208156734'],
       [2, 18, '708796028'],
       [1, 14, '601722048'],
       [2, 4, '900361714'],
       [1, 48, '980077666'],
       [1, 5, '802062761'],
       [1, 12, '500232400'],
       [1, 33, '891092428'],
       [1, 4, '943013339'],
       [1, 9, '330093765'],
       [1, 34, '112032057'],
       [2, 24, '657082333'],
       [1, 15, '473712124'],
       [1, 3, '850204814'],
       [2, 22, '495180247'],
       [1, 6, '069062269'],
       [1, 4, '926837450'],
       [1, 9, '329605225'],
       [1, 48, '983279796'],
       [2, 4, '934584303'],
       [1, 23, '56310'],
       [1, 39, '009213630'],
       [1, 34, '104653013'],
       [1, 4, '931018498'],
       [2, 14, '606172656'],
       [1, 9, '320823228'],
       [1, 35, '436143464'],
       [2, 32, '871104186'],
       [1, 49, '532243500'],
       [1, 34, '115902025'],
       [2, 47, '054465986'],
       [1, 49, '537920001'],
       [1, 14, '602011718'],
 

In [164]:
y = my_data["NPI"]
y[0:5]



0    1396819231
1    1194890707
2    1003981614
3    1912072521
4    1992870505
Name: NPI, dtype: int64

In [165]:
from sklearn.model_selection import train_test_split


In [166]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)
X_trainset

array([[2, 2, '727160445'],
       [1, 16, '666040065'],
       [2, 9, '331662323'],
       ...,
       [2, 25, '387629314'],
       [1, 44, '752844658'],
       [1, 15, '474021149']], dtype=object)

In [167]:
X_trainset.shape

(700, 3)

In [168]:
y_trainset.shape

(700,)

In [169]:
npiTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
npiTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [170]:
npiTree.fit(X_trainset,y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [171]:
predTree = npiTree.predict(X_testset)

In [172]:
print (predTree [0:5])
print (y_testset [0:5])

[1013138247 1003296369 1013934140 1013934140 1003294372]
642    1083684419
762    1235109570
909    1982621017
199    1710904099
586    1073687927
Name: NPI, dtype: int64


In [173]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

DecisionTrees's Accuracy:  0.0
