In [26]:
import numpy as np 
import pandas as pd
import sys
from sklearn.tree import DecisionTreeClassifier

In [7]:
my_data = pd.read_csv("train.csv", delimiter=",")
my_data_1 = pd.read_csv("test.csv", delimiter=",")
my_data_1[0:8]



NPI                          PROVIDERNAME  ENTITY_TYPE_CODE  \
0  NaN            GUSKY-SHARP, KATHLEEN NONE                 1   
1  NaN                TARTLER, ADRIAN LASZLO                 1   
2  NaN                    MONIKA RUKUS, INC.                 2   
3  NaN                    JAFORD ENTERPRISES                 2   
4  NaN                         OLANO, ANNA A                 1   
5  NaN  DEPENDABLE CARE TRANSPORTATION, INC.                 2   
6  NaN                      YOUNG, JOSEPHINE                 1   
7  NaN               GUSTAFSON, HEATHER LYNN                 1   

              P_O_N_LEGAL_BUSINESS_NAME       P_F_L_B_M_ADDRESS  \
0                                   NaN       105 VISTA VIEW DR   
1                                   NaN        311 N QUENTIN ST   
2                    MONIKA RUKUS, INC.    8901 CONNECTICUT AVE   
3                    JAFORD ENTERPRISES            PO BOX 86028   
4                                   NaN    100 E IRVING PARK RD   
5  DEPENDABLE CARE TRANSPORTATION, INC.  639 N FAIRFAX AVE FL 2   
6                                   NaN        14711 NE 29TH PL   
7                                   NaN         1400 JACKSON ST   

  PROV_B_M_A_CITY_NAME PROV_B_M_A_STATE_NAME  PROV_B_M_A_POSTAL_CODE  \
0           CLOVERDALE                    CA               954253373   
1              WICHITA                    KS               672083714   
2          CHEVY CHASE                    MD               208156734   
3          BATON ROUGE                    LA               708796028   
4              ROSELLE                    IL               601722048   
5          LOS ANGELES                    CA               900361714   
6             BELLEVUE                    WA               980077666   
7               DENVER                    CO               802062761   

  PROV_B_M_A_CNT_CODE_OUT_US  PROV_B_M_A_TELEPHONE_NUMBER  \
0                         US                 7.078947e+09   
1                         US                 3.166509e+09   
2                         US                 3.019870e+09   
3                         US                 2.252910e+09   
4                         US                 6.304390e+09   
5                         US                 3.238783e+09   
6                         US                          NaN   
7                         US                 3.033884e+09   

                   ...                   AUTH_OFF_FRST_NAME  \
0                  ...                                  NaN   
1                  ...                                  NaN   
2                  ...                               MONIKA   
3                  ...                             SHEVELLE   
4                  ...                                  NaN   
5                  ...                                YEFIM   
6                  ...                                  NaN   
7                  ...                                  NaN   

  AUTH_OFF_MIDDLE_NAME AUTH_OFF_TITLE_OR_POSITION  AUTH_OFF_TELEPHONE_NUMBER  \
0                  NaN                        NaN                        NaN   
1                  NaN                        NaN                        NaN   
2                   L.                      OWNER               3.019870e+09   
3                LIESA                        PIC               2.252910e+09   
4                  NaN                        NaN                        NaN   
5                  NaN                  PRESIDENT               3.236173e+09   
6                  NaN                        NaN                        NaN   
7                  NaN                        NaN                        NaN   

  H_P_T_CODE_1  PROV_LIC_NUM_1 PROV_LIC_NUM_STATE_CODE_1 H_P_P_T_SWITCH_1  \
0   171W00000X         CAOT#12                        CA                Y   
1   111NI0900X         T-00986                        KS                Y   
2   101YM0800X           08641                        MD                Y   
3   3336

In [8]:
my_data_1 = my_data_1[0:35]

In [9]:

sys.getsizeof(my_data)/(1024*1024*1024)
np.unique(my_data["PROV_B_M_A_STATE_NAME"])
np.unique(my_data_1["PROV_B_M_A_STATE_NAME"])

array(['AZ', 'CA', 'CO', 'CT', 'FL', 'IA', 'IL', 'IN', 'KS', 'LA', 'MD',
       'MI', 'MN', 'MO', 'NM', 'NV', 'NY', 'OH', 'PR', 'VT', 'WA', 'WI'],
      dtype=object)

In [10]:
X = my_data[['ENTITY_TYPE_CODE',  'PROV_B_M_A_STATE_NAME', 'PROV_B_M_A_POSTAL_CODE', 'SPECDESC']].values
X_1 = my_data_1[['ENTITY_TYPE_CODE',  'PROV_B_M_A_STATE_NAME', 'PROV_B_M_A_POSTAL_CODE', 'SPECDESC']].values
X[0:3]

array([[1, 'CA', 954253373, 'Contractor'],
       [1, 'KS', 672083714, 'Internist'],
       [2, 'MD', 208156734, 'Mental Health']], dtype=object)

In [11]:
from sklearn import preprocessing
le_STATE_NAME = preprocessing.LabelEncoder()
le_STATE_NAME.fit(np.unique(my_data["PROV_B_M_A_STATE_NAME"]))
X[:,1] = le_STATE_NAME.transform(X[:,1]) 

le_SPECDESC = preprocessing.LabelEncoder()
le_SPECDESC.fit(np.unique(my_data["SPECDESC"]))
X[:,3] = le_SPECDESC.transform(X[:,3]) 

le_STATE_NAME_1 = preprocessing.LabelEncoder()
le_STATE_NAME_1.fit(np.unique(my_data_1["PROV_B_M_A_STATE_NAME"]))
X_1[:,1] = le_STATE_NAME_1.transform(X_1[:,1]) 

le_SPECDESC_1 = preprocessing.LabelEncoder()
le_SPECDESC_1.fit(np.unique(my_data_1["SPECDESC"]))
X_1[:,3] = le_SPECDESC_1.transform(X_1[:,3]) 




In [12]:
X[0:100]

array([[1, 1, 954253373, 8],
       [1, 9, 672083714, 14],
       [2, 12, 208156734, 15],
       [2, 11, 708796028, 7],
       [1, 7, 601722048, 23],
       [2, 1, 900361714, 17],
       [1, 26, 980077666, 21],
       [1, 2, 802062761, 29],
       [1, 6, 500232400, 4],
       [1, 18, 891092428, 21],
       [1, 1, 943013339, 24],
       [1, 5, 330093765, 13],
       [1, 19, 112032057, 28],
       [2, 15, 657082333, 19],
       [1, 8, 473712124, 4],
       [1, 0, 850204814, 4],
       [2, 13, 495180247, 6],
       [1, 3, 69062269, 12],
       [1, 1, 926837450, 15],
       [1, 5, 329605225, 20],
       [1, 26, 983279796, 16],
       [2, 1, 934584303, 3],
       [1, 14, 56310, 0],
       [1, 22, 9213630, 13],
       [1, 19, 104653013, 21],
       [1, 1, 931018498, 15],
       [2, 7, 606172656, 9],
       [1, 5, 320823228, 20],
       [1, 20, 436143464, 23],
       [2, 17, 871104186, 1],
       [1, 27, 532243500, 28],
       [1, 19, 115902025, 4],
       [2, 25, 54465986, 2],
       [1, 27,

In [13]:
y = my_data["NPI"]
y[0:5]



0    1396819231
1    1194890707
2    1003981614
3    1912072521
4    1992870505
Name: NPI, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split


In [15]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)
X_trainset

array([[1, 1, 931018498, 15],
       [2, 13, 495180247, 6],
       [1, 0, 850204814, 4],
       [1, 27, 532243500, 28],
       [1, 5, 330093765, 13],
       [1, 2, 802062761, 29],
       [1, 23, 372043101, 13],
       [1, 5, 320823228, 20],
       [1, 7, 602011718, 21],
       [1, 26, 981552713, 18],
       [2, 1, 900361714, 17],
       [2, 21, 152032348, 10],
       [1, 9, 672083714, 14],
       [1, 19, 132031652, 5],
       [2, 12, 208156734, 15],
       [1, 14, 56310, 0],
       [1, 27, 537920001, 22],
       [1, 3, 69062269, 12],
       [2, 7, 606172656, 9],
       [1, 8, 473712124, 4],
       [2, 17, 871104186, 1],
       [1, 26, 983279796, 16],
       [2, 25, 54465986, 2],
       [1, 5, 336152872, 11],
       [1, 16, 27858, 25],
       [1, 13, 486248407, 5],
       [1, 5, 327467403, 23],
       [1, 1, 943013339, 24],
       [1, 5, 329605225, 20],
       [2, 1, 934584303, 3],
       [1, 1, 954253373, 8],
       [1, 6, 500232400, 4],
       [2, 11, 708796028, 7],
       [1, 19, 104

In [16]:
X_trainset.shape

(35, 4)

In [17]:
y_trainset.shape

(35,)

In [18]:
npiTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
npiTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [19]:
npiTree.fit(X_trainset,y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
predTree = npiTree.predict(X_1[0:4])
X_1[0:5]

array([[1, 1, 954253373, 7],
       [1, 8, 672083714, 11],
       [2, 10, 208156734, 12],
       [2, 9, 708796028, 6],
       [1, 6, 601722048, 19]], dtype=object)

In [21]:
print (predTree [0:5])


[1396819231 1164597779 1003981614 1205901824]


In [22]:
X_1[0:1]



array([[1, 1, 954253373, 7]], dtype=object)

In [23]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

ValueError: Found input variables with inconsistent numbers of samples: [15, 4]

In [25]:
X_testset


array([[1, 19, 112032057, 28],
       [1, 5, 335115911, 26],
       [1, 18, 891092428, 21],
       [1, 14, 55350, 27],
       [1, 19, 115902025, 4],
       [1, 20, 436143464, 23],
       [2, 15, 657082333, 19],
       [1, 4, 200072113, 18],
       [1, 24, 770821658, 20],
       [1, 26, 980077666, 21],
       [1, 7, 601722048, 23],
       [1, 22, 9213630, 13],
       [1, 10, 410113775, 5],
       [1, 1, 926837450, 15],
       [1, 7, 601722048, 23]], dtype=object)