In [1]:
import numpy as np 
import pandas as pd
import sys
from sklearn.tree import DecisionTreeClassifier

In [2]:
my_data = pd.read_csv("training_2.csv", delimiter=",")



In [3]:

#sys.getsizeof(my_data)/(1024*1024*1024)
#np.unique(my_data["PROV_B_M_A_STATE_NAME"])

In [4]:
X = my_data[['ENTITY_TYPE_CODE','PROVIDERNAME', 'PROV_B_M_A_STATE_NAME', 'PROV_B_M_A_POSTAL_CODE', 'SPECDESC','PROV_B_P_B_P_LOC_ADD_TEL_NUM','PROV_B_M_A_CITY_NAME','PRIMARY_TAXONOMY']].values
#X[0:3]


In [5]:
from sklearn import preprocessing

le_PROVIDERNAME = preprocessing.LabelEncoder()
le_PROVIDERNAME.fit(np.unique(my_data["PROVIDERNAME"]))
X[:,1] = le_PROVIDERNAME.transform(X[:,1]) 

le_STATE_NAME = preprocessing.LabelEncoder()
le_STATE_NAME.fit(np.unique(my_data["PROV_B_M_A_STATE_NAME"]))
X[:,2] = le_STATE_NAME.transform(X[:,2]) 

le_SPECDESC = preprocessing.LabelEncoder()
le_SPECDESC.fit(np.unique(my_data["SPECDESC"]))
X[:,4] = le_SPECDESC.transform(X[:,4]) 

le_CITY_NAME = preprocessing.LabelEncoder()
le_CITY_NAME.fit(np.unique(my_data["PROV_B_M_A_CITY_NAME"]))
X[:,6] = le_CITY_NAME.transform(X[:,6]) 


le_PRIMARY_TAXONOMY = preprocessing.LabelEncoder()
le_PRIMARY_TAXONOMY.fit(np.unique(my_data["PRIMARY_TAXONOMY"]))
X[:,7] = le_PRIMARY_TAXONOMY.transform(X[:,7]) 

 






In [6]:
#X[0:100]

In [7]:
y = my_data["NPI"]
y[0:5]



0    1396819231
1    1194890707
2    1003981614
3    1912072521
4    1992870505
Name: NPI, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split


In [9]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)
X_trainset

array([[1, 47, 21, ..., 4193857755, 43, 21],
       [1, 47, 21, ..., 4193857755, 43, 21],
       [2, 0, 2, ..., 3238782660, 25, 29],
       ...,
       [2, 2, 0, ..., 5053400700, 0, 31],
       [0, 38, 17, ..., 2523553177, 17, 2],
       [2, 45, 0, ..., 4172350707, 28, 10]], dtype=object)

In [10]:
X_trainset.shape

(2377, 8)

In [11]:
y_trainset.shape

(2377,)

In [12]:
npiTree = DecisionTreeClassifier(criterion="entropy", max_depth = 5)
npiTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [13]:
npiTree.fit(X_trainset,y_trainset)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [14]:
predTree = npiTree.predict(X_testset)

In [15]:
print (predTree [0:5])
print (y_testset [0:5])

[1790850303 1144395757 1144395757 1427122274 1295800811]
1092    1194890715
894     1033283890
1444    1033283890
972     1790859544
1631    1295800811
Name: NPI, dtype: int64


In [16]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

DecisionTrees's Accuracy:  0.5976447497546614


In [17]:
np.take(my_data,np.random.permutation(my_data.shape[0]),axis=0)


NPI                          PROVIDERNAME  ENTITY_TYPE_CODE  \
735   1922173541                     MCGEE, JAMES MATT                 1   
2935  1053485896                                     0                 1   
625   1518031368                JONES, STEPHEN MATTHEW                 0   
2076  1164597779                                     0                 1   
3127  1023183647                      PALMATIER, JANET                 1   
2068  1396819231                                     0                 1   
2180  1841365467   ADIRONDACK AUDIOLOGY ASSOCIATES, PC                 2   
2154  1265507875                      YOUNG, JOSEPHINE                 1   
2090  1982778734                                     0                 1   
1912  1336213180                   FALDEN, ALLISON ANN                 1   
780   1578638193           HARTMAN, AMANDA GRACE SCOTT                 1   
470   1780758524          SMITH-FORBES, ENRIQUE VICTOR                 1   
3273  1932274552                                     0                 1   
1127  1396810917                                     0                 1   
2576  1205901824                 ANCHORING LIGHT, INC.                 2   
1921  1487729000               BEHAR-HORWITZ, LYNDA M.                 1   
2574  1336213180                   FALDEN, ALLISON ANN                 1   
1826  1396810917                  WEBSTER, JOHN THOMAS                 0   
1354  1801961412  DEPENDABLE CARE TRANSPORTATION, INC.                 0   
60    1790850303                   WEINGARTEN, RANDALL                 1   
1996  1760556526                                     0                 1   
3236  1013082635                      AXEL, JONATHAN P                 1   
1223  1992870505                                     0                 1   
760   1851466460                     BADGE, JAMES JOHN                 1   
2543  1396819231            GUSKY-SHARP, KATHLEEN NONE                 1   
16    1760557375     CASCADE MEDICAL TESTING LAB, INC.                 2   
403   1750456372                                     0                 1   
3231  1669547287                          MASRI, ELIAS                 1   
1517  1053485896                         VO, CHRISTINE                 1   
815   1780758524          SMITH-FORBES, ENRIQUE VICTOR                 0   
...          ...                                   ...               ...   
2661  1124193735                SCHMIT, EDWARD CHARLES                 0   
1169  1780758524                                     0                 1   
26    1427122274           STEWART G WILLOUGHBY DDS PC                 2   
825   1023183647                      PALMATIER, JANET                 0   
675   1518031368                JONES, STEPHEN MATTHEW                 1   
221   1669547287                          MASRI, ELIAS                 1   
3339  1851465611                 FISCHER, CINDY JOLENE                 1   
1379  1023183647                                     0                 1   
1014  1396810917                  WEBSTER, JOHN THOMAS                 1   
2931  1124193735                                     0                 1   
2807  1790850303                                     0                 1   
603   1912072521                    JAFORD ENTERPRISES                 0   
1658  1124193735                SCHMIT, EDWARD CHARLES                 0   
2109  1740355361                                     0                 1   
2315  1679648281                       DETTMER, ROBERT                 0   
2480  1295800811                    RUTAR, STACIE HOPE                 1   
1343  1124192984                    ROBERTSON, BETTY P                 1   
672   1982778734                       RAND, BECKY MAY                 1   
2811  1124193735                                     0                 1   
1121  1982778734                                     0                 1   
1712  1124193735                SCHMIT, EDWARD CHARLES       

In [18]:
file1 = "test2.csv"
input = pd.read_csv(file1, delimiter=",")


In [19]:
input

NPI                         PROVIDERNAME  ENTITY_TYPE_CODE  \
0  NaN                   MONIKA RUKUS, INC.                 2   
1  NaN                         MOSS, PAUL R                 1   
2  NaN               SCHMIT, EDWARD CHARLES                 1   
3  NaN                        VO, CHRISTINE                 1   
4  NaN                     SANCHEZ, ROBERTO                 1   
5  NaN                 WEBSTER, JOHN THOMAS                 1   
6  NaN  ADIRONDACK AUDIOLOGY ASSOCIATES, PC                 2   
7  NaN                   RUTAR, STACIE HOPE                 1   
8  NaN      ONCOLOGY HEMATOLOGY ASSOCIATION                 2   
9  NaN                FISCHER, CINDY JOLENE                 1   

             P_O_N_LEGAL_BUSINESS_NAME             P_F_L_B_M_ADDRESS  \
0                   MONIKA RUKUS, INC.          8901 CONNECTICUT AVE   
1                                  NaN                1932 SW 3RD ST   
2                                  NaN                 207 W MAIN ST   
3                                  NaN          15721 POINSETTIA WAY   
4                                  NaN          1755 AVE PAZ GRANELA   
5                                  NaN               1614 S BYRNE RD   
6  ADIRONDACK AUDIOLOGY ASSOCIATES, PC  356 MOUNTAIN VIEW DR STE 101   
7                                  NaN                503 FARRELL DR   
8      ONCOLOGY HEMATOLOGY ASSOCIATION                2 HOT METAL ST   
9                                  NaN          724 HARRINGTON ST SW   

  PROV_B_M_A_CITY_NAME PROV_B_M_A_STATE_NAME  PROV_B_M_A_POSTAL_CODE  \
0          CHEVY CHASE                    MD               208156734   
1               ANKENY                    IA               500232400   
2             PORTLAND                    IN               473712124   
3          WESTMINSTER                    CA               926837450   
4             SAN JUAN                    PR                 9213630   
5               TOLEDO                    OH               436143464   
6           COLCHESTER                    VT                54465986   
7            COVINGTON                    KY               410113775   
8           PITTSBURGH                    PA               152032348   
9           HUTCHINSON                    MN                   55350   

  PROV_B_M_A_CNT_CODE_OUT_US  PROV_B_M_A_TELEPHONE_NUMBER  \
0                         US                   3019869999   
1                         US                   5159649114   
2                         US                   2607269661   
3                         US                   7148949078   
4                         US                   7877928200   
5                         US                   4193857755   
6                         US                   8029229545   
7                         US                   8593313292   
8                         US                   4124327706   
9                         US                   3202354613   

                       ...                      AUTH_OFF_FRST_NAME  \
0                      ...                                  MONIKA   
1                      ...                                     NaN   
2                      ...                                     NaN   
3                      ...                                     NaN   
4                      ...                                     NaN   
5                      ...                                     NaN   
6                      ...                                   KEITH   
7                      ...                                     NaN   
8                      ...                                 RICHARD   
9                      ...                                     NaN   

  AUTH_OFF_MIDDLE_NAME AUTH_OFF_TITLE_OR_POSITION  AUTH_OFF_TELEPHONE_NUMBER  \
0                   L.                      OWNER               3.019870e+09   
1                  NaN                        NaN                        NaN   
2                 

In [20]:

X_1 = input[['ENTITY_TYPE_CODE','PROVIDERNAME', 'PROV_B_M_A_STATE_NAME', 'PROV_B_M_A_POSTAL_CODE', 'SPECDESC','PROV_B_P_B_P_LOC_ADD_TEL_NUM','PROV_B_M_A_CITY_NAME','PRIMARY_TAXONOMY']].values
X[0:3]


array([[1, 19, 2, 954253373, 9, 7078947409, 10, 13],
       [1, 44, 10, 672083714, 15, 3169460990, 48, 6],
       [2, 30, 13, 208156734, 16, 3019869999, 8, 1]], dtype=object)

In [21]:
from sklearn import preprocessing

le_PROVIDERNAME = preprocessing.LabelEncoder()
le_PROVIDERNAME.fit(np.unique(my_data["PROVIDERNAME"]))
X_1[:,1] = le_PROVIDERNAME.transform(X_1[:,1]) 

le_STATE_NAME = preprocessing.LabelEncoder()
le_STATE_NAME.fit(np.unique(my_data["PROV_B_M_A_STATE_NAME"]))
X_1[:,2] = le_STATE_NAME.transform(X_1[:,2]) 

le_SPECDESC = preprocessing.LabelEncoder()
le_SPECDESC.fit(np.unique(my_data["SPECDESC"]))
X_1[:,4] = le_SPECDESC.transform(X_1[:,4]) 

le_CITY_NAME = preprocessing.LabelEncoder()
le_CITY_NAME.fit(np.unique(my_data["PROV_B_M_A_CITY_NAME"]))
X_1[:,6] = le_CITY_NAME.transform(X_1[:,6]) 


le_PRIMARY_TAXONOMY = preprocessing.LabelEncoder()
le_PRIMARY_TAXONOMY.fit(np.unique(my_data["PRIMARY_TAXONOMY"]))
X_1[:,7] = le_PRIMARY_TAXONOMY.transform(X_1[:,7]) 

 

In [22]:
predTree = npiTree.predict(X_1)

In [23]:
predTree

array([1003981614, 1164597779, 1124193735, 1053485896, 1427122274,
       1205901824, 1841365467, 1295800811, 1790850303, 1851465611],
      dtype=int64)

In [24]:

df = pd.DataFrame (predTree)

#filepath = 'file.txt'
#df.savetxt(filepath, index=False)

In [25]:
np.savetxt(r'np1.txt', df.values, fmt='%d')